version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: price-comparator-application
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretPassword123@
      POSTGRES_DB: price_comparator_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
